services:
#    rabbit_mq.example:
#        class: Jaimongo\RabbitMQBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    rabbit_publisher:
        class: Jaimongo\RabbitMQBundle\Services\PublisherService
        arguments: ["@service_container", "%rabbit_mq.connection.queue%", "%rabbit_mq.connection.exchange%"]
